all:
  children:
    honeypot:
      hosts:
        cowrie:
          ansible_host: "135.225.92.119"
    siem:
      hosts:
        wazuh:
          ansible_host: "135.225.55.204"
  vars:
    ansible_user: azadmin
    ansible_ssh_private_key_file: ~/.ssh/homelab_vm_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
